### ISSUE TITLE
Error trying to install ssw in R version 4.0.2

### ISSUE THREAD

**Issue by mantzaris** [nanxstats/ssw-r#2]
I upgraded R to the most recent version, 4.0.2 and tried installing `ssw` again and have received an error:

```
> library("ssw")
Error: package or namespace load failed for ‘ssw’:
 package ‘ssw’ was installed before R 4.0.0: please re-install it
> install.packages("ssw")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘ssw’ is not available (for R version 4.0.2) 
```
EDIT: I tried `remotes::install_github("nanxstats/ssw-r")` as the documentation in the README.md describes, and that did not work either.

**Comment by nanxstats** [comment]
@mantzaris Oh, the package is not on CRAN, so please use remotes to install it:

```r
remotes::install_github("nanxstats/ssw-r")
```

**Comment by mantzaris** [comment]
I managed to solve the issue by using this command prior to the statement `library("ssw")`:

`Sys.setenv(RETICULATE_PYTHON = "/usr/bin/python3")`
